# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_ci
  end

  desc "TestFlight 업로드"
  lane :beta do
    api_key = app_store_connect_api_key(
        key_id: ENV["ASC_KEY_ID"],
        issuer_id: ENV["ASC_ISSUER_ID"],
        key_content: ENV["ASC_KEY_CONTENT"],
        is_key_content_base64: true
    )

    match(type: "appstore")
    latest_build = latest_testflight_build_number(api_key: api_key)

    increment_build_number(
      build_number: latest_build + 1,
      xcodeproj: "Atcha-iOS.xcodeproj"
    )

    build_app(
      project: "Atcha-iOS.xcodeproj",  
      scheme: "Atcha-Stage",   
      configuration: "Stage",         
      clean: true,
      export_method: "app-store",
      xcargs: "CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER='match AppStore com.atcha.iOS'"
    )

    upload_to_testflight(api_key: api_key)
  end

  desc "App Store 업로드 (Submit은 안 함)"
  lane :release do

    api_key = app_store_connect_api_key(
        key_id: ENV["ASC_KEY_ID"],
        issuer_id: ENV["ASC_ISSUER_ID"],
        key_content: ENV["ASC_KEY_CONTENT"],
        is_key_content_base64: true
    )

    match(type: "appstore")

    latest_build = latest_testflight_build_number(api_key: api_key)

    increment_build_number(
      build_number: latest_build + 1,
      xcodeproj: "Atcha-iOS.xcodeproj"
    )

    build_app(
      project: "Atcha-iOS.xcodeproj",
      scheme: "Atcha-Live",              
      configuration: "Release",     
      clean: true
    )

    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      is_key_content_base64: true
    )

    deliver(
      api_key: api_key,
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false,
      force: true,
      run_precheck_before_submit: false
    )
  end
end