# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: Debug toolchain
        run: |
          xcodebuild -version
          xcodebuild -showsdks
          xcrun simctl list runtimes

      - name: Download iOS Platform
        run: xcodebuild -downloadPlatform iOS

      - name: Create Dummy Config
        run: |
          touch DevConfig.xcconfig
          echo "// Dummy Config for CI" >> DevConfig.xcconfig
          
      - name: Build (Any iOS Device)
        run: |
          xcodebuild \
            -project Atcha-iOS.xcodeproj \
            -scheme Atcha-iOS \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            -sdk iphoneos \
            IPHONEOS_DEPLOYMENT_TARGET=16.1 \
            FRAMEWORK_SEARCH_PATHS='$(inherited) $(PROJECT_DIR)' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            AD_HOC_CODE_SIGNING_ALLOWED=YES \
            clean build
